#!/bin/bash

# requires: autoconf, libtool, libreadline-dev

# For grid5000
# sudo-g5k apt-get install uuid-dev libtool-bin
set -e

mkdir -p ext
cd ext

ZOOKEEPER_VERSION="3.4.11"
GOOGLETEST_VERSION="1.8.0"

# zookeeper
wget "http://apache.org/dist/zookeeper/zookeeper-$ZOOKEEPER_VERSION/zookeeper-$ZOOKEEPER_VERSION.tar.gz"
tar xzf "zookeeper-$ZOOKEEPER_VERSION.tar.gz"
rm "zookeeper-$ZOOKEEPER_VERSION.tar.gz"
mv "zookeeper-$ZOOKEEPER_VERSION/src/c" zookeeper
rm -fr "zookeeper-$ZOOKEEPER_VERSION"
cd zookeeper
./configure --prefix=$PWD
make -j7
cd ..

# # protobuf
git clone https://github.com/google/protobuf.git
cd protobuf
git checkout "3.3.x"
./autogen.sh
./configure --prefix=$PWD
make -j7
cd ..

# googletest
wget "https://github.com/google/googletest/archive/release-${GOOGLETEST_VERSION}.zip" -O googletest.zip
unzip googletest
rm googletest.zip
cd "googletest-release-${GOOGLETEST_VERSION}"
mkdir -p build && cd build
cmake ..
make -j7
cd ../..

# zeromq
wget https://archive.org/download/zeromq_2.1.11/zeromq-2.1.11.tar.gz
tar xzf zeromq-2.1.11.tar.gz
rm zeromq-2.1.11.tar.gz
mv zeromq-2.1.11 zeromq
cd zeromq
./autogen.sh
./configure --prefix=$PWD --enable-static
make -j7
cd ..

# util-linux
wget https://www.kernel.org/pub/linux/utils/util-linux/v2.31/util-linux-2.31.1.tar.gz
tar xzf util-linux-2.31.1.tar.gz
rm util-linux-2.31.1.tar.gz
mv util-linux-2.31.1 util-linux
cd util-linux
./autogen.sh
./configure --enable-static
make
